apiVersion: v1
kind: Service
metadata:
  name: port-authorizing
  namespace: port-authorizing
  labels:
    app: port-authorizing
spec:
  type: ClusterIP  # Change to LoadBalancer or NodePort for external access
  selector:
    app: port-authorizing
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
  sessionAffinity: ClientIP  # Important for WebSocket connections

